### PR TITLE
Undefined name: from six.moves import xrange

### PR DESCRIPTION
**Pull request by cclauss**
[flake8](http://flake8.pycqa.org) testing of https://github.com/IBM/MAX-Image-Completer on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./core/utils.py:155:16: F821 undefined name 'xrange'
    for idx in xrange(100):
               ^
./core/utils.py:165:48: F821 undefined name 'xrange'
    for idx in [random.randint(0, 99) for _ in xrange(100)]:
                                               ^
./core/utils.py:177:16: F821 undefined name 'xrange'
    for idx in xrange(100):
               ^
./core/utils.py:189:16: F821 undefined name 'xrange'
    for idx in xrange(100):
               ^
4     F821 undefined name 'xrange'
4
```

__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by dolph** [comment]
FWIW, we did some analysis on `xrange()` vs `range()` in py2 and py3 in OpenStack, and unless you had millions of iterations in `xrange()`, `range()` performed just fine in py2 and py3 and it wasn't worth using `six.xrange()`.

**Comment by cclauss** [comment]
It does create a large memory allocation:
```
$ python2
>>> import sys
>>> sys.getsizeof(xrange(1000000))
40
>>> sys.getsizeof(range(1000000))
8000072
```

**Comment by dolph** [comment]
> unless you had millions of iterations

All the usages here are less than:

```
>>> sys.getsizeof(range(100))
872
```

So, then consider the cost of importing `six`.

**Comment by cclauss** [comment]
I am OK to convert all instances of __xrange()__ --> __range()__ and drop the __six__ import.

**Pull request merged**
